### ISSUE TITLE
error downloding mods 

### ISSUE THREAD

**Issue by billythejew456** [hrt/HeroHunter#22]
if click on mods on the krunker menu and try ro install any it dosent work it just shows mod error

**Comment by hrt** [comment]
Probably because I block any unknown scripts loaded from krunker.io to stop any anti cheat updates. It also breaks the social links I think.

I may look into it but letting more scripts run makes it less safe from krunker anti cheat updates

**Comment by billythejew456** [comment]
you dont need to change if it makes it less safe form krunker anti cheat updates i was just wondering why it happened thanks for getting back to me though

**Comment by redr4dier** [comment]
Yes it breaks the social links.

**Comment by hrt** [comment]
@redr4dier  fyi I fixed social links but it requires re downloading the extension
