### ISSUE TITLE
Some suggestions.

### ISSUE THREAD

**Issue by Heraku69** [hrt/HeroHunter#25]
You should have everything selectable, like the no recoil, no spread, tracers, etc. When you turn off the ESP you can still see it when an enemy is visible which I also think should be selectable. In the future you should add savable configs, a way to edit how smooth the aimbot is, and chams, like the chams in CS.

**Comment by hrt** [comment]
Lmao i want to keep the cheat simple. I think the options it has right now is too many itself

**Comment by Heraku69** [comment]
> Lmao i want to keep the cheat simple. I think the options it has right now is too many itself

At least add 360, xd.

**Comment by GreatCheat** [comment]
For 360* i would recommend


```
unsafeWindow.control.object.rotation.y -= 10;
unsafeWindow.control.xDr -= 10;
unsafeWindow.control.xVel -= 10;
```

Going on...

```
if (ticks > 0) {
			this.spinTicks = this.spinTicks + 1;
			unsafeWindow.control.object.rotation.y -= 4;
			unsafeWindow.control.yDr -= 4;

			unsafeWindow.control.xDr -= 4;
			unsafeWindow.control.xVel -= 6.2;
```

**Comment by hrt** [comment]
I mean 360 is hella useless imo but if you really want it I'll add it later. I feel it's such a waste of a menu option

**Comment by GreatCheat** [comment]
Killing an enemy while playing a Sniper class and doing 360* turn grants you +150 bonus score :)

More score = faster lvl up and easier KR :)

**Comment by redr4dier** [comment]
Btw is the aimbot fixed and do i have to redownload the extension?

**Comment by hrt** [comment]
It's fixed and you don't have to redownload if you had an auto update version installed

**Comment by hrt** [comment]
> For 360* i would recommend
> 
> ```
> unsafeWindow.control.object.rotation.y -= 10;
> unsafeWindow.control.xDr -= 10;
> unsafeWindow.control.xVel -= 10;
> ```
> 
> Going on...
> 
> ```
> if (ticks > 0) {
> 			this.spinTicks = this.spinTicks + 1;
> 			unsafeWindow.control.object.rotation.y -= 4;
> 			unsafeWindow.control.yDr -= 4;
> 
> 			unsafeWindow.control.xDr -= 4;
> 			unsafeWindow.control.xVel -= 6.2;
> ```

Those numbers seem to be picked out of thin air -> quite inefficient

360s are calculated by the how much (at least 360 degrees) you've turned in a single direction in the past ```c.spinTimer / c.serverTickRate``` ticks. spinTimer  is default 1800 and serverTickRate is default 1e3 / 30, so the last 53 ticks which is the past ~1.59 seconds of game play.

The amount you can spin per tick is calculated using
```        }, t.exports.getAngleDist = function(t, e) {
            return Math.atan2(Math.sin(e - t), Math.cos(t - e))
        }```

So the max rotation in a single tick is 180 which means we only need to waste 2 ticks per 53 ticks to achieve constant 360 rotation.

```
        }, this.saveSpin = function(t, e) {
            l && (t.spins.unshift(e), t.spins.length > c.spinTimer / c.serverTickRate && (t.spins.length = Math.round(c.spinTimer / c.serverTickRate)))
        }, this.getSpin = function(t) {
            for (var e = 0, n = 0; n < t.spins.length; ++n) e += t.spins[n];
            return Math.abs(e * (180 / Math.PI))
        
```

**Comment by hrt** [comment]
Pushed update, should be visible in few mins
