### ISSUE TITLE
anti cheat suspicious behavior

### ISSUE THREAD

**Issue by billythejew456** [hrt/HeroHunter#34]
document.querySelector("script[src*='js/game']")?'load':'loadgg'

and for some reason i cant join any games without benig put back in the game i was trying to leave

**Comment by hrt** [comment]
Yeah they made a redundant change, I think they're just trying to break cheats or something useless.

FYI, I haven't pushed an update for 1.5.0 https://github.com/hrt/HeroHunter/issues/32

**Comment by billythejew456** [comment]
oh well the new anti cheat makes it so everyone using the script cant join any other games apart from ones filled with people using the same one thanks for getting back to me

**Comment by hrt** [comment]
@billythejew456  that sounds pretty fkn sick for me because I only like playing against cheaters but can you check if you are cheater flagged - I rarely find a cheater myself and their anti cheat is still absolutely useless

**Comment by billythejew456** [comment]
@hrt im not witch is strange and im still in the same game even though i opend krunker in a new tab

**Comment by hrt** [comment]
@billythejew456  can you send me the game link :D

**Comment by billythejew456** [comment]
@hrt ok https://krunker.io/?game=FRA:p5vs9

**Comment by hrt** [comment]
@billythejew456  the game kicks me out of that server for 'invalid version'. If I had to guess it's either because france is really far away from me (insane ping) or because the server is for hackers only and my account isn't flagged

**Comment by billythejew456** [comment]
@hrt or everyone is using anti lag im in the uk and i have like 22 ping

**Comment by hrt** [comment]
@billythejew456  actually it's interesting because I think this server is using an old version of the game lol..

**Comment by billythejew456** [comment]
@hrt it might be that would explain why i cant leave

**Comment by hrt** [comment]
@billythejew456  turn your hacks off and see if you get invalid version

**Comment by billythejew456** [comment]
@hrt yeah i do that is so cool  :D

**Comment by hrt** [comment]
@billythejew456 Lol, Krunker has confirmed got servers for old versions of the game - if you're using old cheats you are on old version of the game so you will be sent to those servers. I do not think they did this intentionally.

**Comment by billythejew456** [comment]
@hrt lol thats a major fuck up right there but its a super cool fuck up
